import { useState, type FormEvent } from 'react'
import { ArrowRight, FileSearch, LockKeyhole, Sparkles } from 'lucide-react'
import { Navigate } from 'react-router-dom'
import { useAuth } from '../AuthContext'

export function AuthPage() {
  const auth = useAuth(); const [mode, setMode] = useState<'login' | 'register'>('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  if (auth.email) return <Navigate to="/documents" replace />
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await auth[mode](email, password) } catch (e) { setError(e instanceof Error ? e.message : 'Something went wrong') } finally { setBusy(false) } }
  return <div className="grid min-h-screen bg-ink lg:grid-cols-2">
    <section className="relative hidden overflow-hidden p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -left-32 top-20 h-96 w-96 rounded-full bg-emerald-400/10 blur-3xl"/><div className="relative flex items-center gap-3 text-lg font-bold"><span className="grid h-10 w-10 place-items-center rounded-xl bg-mint text-ink"><Sparkles size={20}/></span>DocuChat AI</div><div className="relative max-w-xl"><p className="mb-4 text-sm font-bold uppercase tracking-[.2em] text-mint">Answers you can verify</p><h1 className="text-5xl font-extrabold leading-[1.08]">Turn your documents into a conversation.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-300">Upload trusted files, ask natural questions, and get grounded answers with every supporting excerpt attached.</p></div><div className="relative flex gap-8 text-sm text-slate-400"><span>Private workspace</span><span>Source-backed</span><span>Live streaming</span></div></section>
    <section className="flex items-center justify-center bg-slate-50 p-6"><div className="w-full max-w-md"><div className="mb-8 lg:hidden"><span className="inline-flex items-center gap-2 font-bold"><Sparkles className="text-emerald-600"/>DocuChat AI</span></div><div className="card p-7 sm:p-9"><div className="mb-7 grid h-12 w-12 place-items-center rounded-2xl bg-emerald-50 text-emerald-700">{mode === 'login' ? <LockKeyhole/> : <FileSearch/>}</div><h2 className="text-2xl font-bold">{mode === 'login' ? 'Welcome back' : 'Create your workspace'}</h2><p className="mt-2 text-sm text-slate-500">{mode === 'login' ? 'Sign in to continue exploring your documents.' : 'Start asking better questions of your content.'}</p><form className="mt-7 space-y-4" onSubmit={submit}><label className="block text-sm font-semibold">Email<input className="field mt-2" type="email" value={email} onChange={e => setEmail(e.target.value)} required placeholder="you@company.com"/></label><label className="block text-sm font-semibold">Password<input className="field mt-2" type="password" minLength={8} value={password} onChange={e => setPassword(e.target.value)} required placeholder="At least 8 characters"/></label>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button className="btn-primary w-full" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}<ArrowRight size={17}/></button></form><p className="mt-6 text-center text-sm text-slate-500">{mode === 'login' ? 'New to DocuChat?' : 'Already have an account?'} <button className="font-bold text-emerald-700" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError('') }}>{mode === 'login' ? 'Create account' : 'Sign in'}</button></p></div></div></section>
  </div>
}
