import { useCallback, useEffect, useState } from 'react'
import { CheckCircle2, FileText, LoaderCircle, Trash2, UploadCloud, XCircle } from 'lucide-react'
import { api } from '../api'
import type { DocumentItem } from '../types'

export function DocumentsPage() {
  const [documents, setDocuments] = useState<DocumentItem[]>([]); const [dragging, setDragging] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState(''); const [embedder, setEmbedder] = useState('')
  const load = useCallback(async () => { try { setDocuments(await api.documents()) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load documents') } }, [])
  useEffect(() => { void load() }, [load])
  useEffect(() => { api.providers().then(p => setEmbedder(p.activeEmbedding)).catch(() => {}) }, [])
  const upload = async (file?: File) => { if (!file) return; setError(''); setUploading(true); try { await api.upload(file); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Upload failed'); await load() } finally { setUploading(false) } }
  const remove = async (id: string) => { if (!confirm('Delete this document and its indexed chunks?')) return; try { await api.deleteDocument(id); setDocuments(items => items.filter(x => x.id !== id)) } catch (e) { setError(e instanceof Error ? e.message : 'Delete failed') } }
  return <div><div className="mb-8"><p className="text-sm font-bold uppercase tracking-[.16em] text-emerald-700">Knowledge base</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Your documents</h1><p className="mt-2 text-slate-500">Add PDF or TXT files. We’ll split and index their content for grounded answers.{embedder && <span className="ml-1 text-slate-400">Indexed with <span className="font-semibold text-emerald-700">{embedder}</span> embeddings.</span>}</p></div>
    <label onDragOver={e => { e.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={e => { e.preventDefault(); setDragging(false); void upload(e.dataTransfer.files[0]) }} className={`card flex cursor-pointer flex-col items-center border-2 border-dashed px-6 py-12 text-center transition ${dragging ? 'border-emerald-500 bg-emerald-50' : 'hover:border-emerald-300 hover:bg-emerald-50/30'}`}><input className="hidden" type="file" accept=".pdf,.txt,application/pdf,text/plain" onChange={e => void upload(e.target.files?.[0])}/><span className="grid h-14 w-14 place-items-center rounded-2xl bg-ink text-mint">{uploading ? <LoaderCircle className="animate-spin"/> : <UploadCloud/>}</span><h2 className="mt-5 text-lg font-bold">{uploading ? 'Extracting and indexing…' : 'Drop a document here'}</h2><p className="mt-1 text-sm text-slate-500">or click to browse · PDF/TXT · 10 MB maximum</p></label>
    {error && <p className="mt-4 rounded-xl border border-red-100 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="mt-8 card overflow-hidden"><div className="border-b px-5 py-4"><h2 className="font-bold">Indexed files <span className="ml-1 text-sm font-medium text-slate-400">{documents.length}</span></h2></div>{documents.length === 0 ? <div className="px-5 py-14 text-center text-sm text-slate-500">Your knowledge base is empty. Upload your first document above.</div> : <ul className="divide-y">{documents.map(doc => <li key={doc.id} className="flex items-center gap-4 px-5 py-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600"><FileText size={20}/></span><div className="min-w-0 flex-1"><p className="truncate font-semibold">{doc.fileName}</p><p className="mt-1 text-xs text-slate-400">{new Date(doc.uploadedAt).toLocaleString()} · {doc.chunkCount} chunks</p>{doc.error && <p className="mt-1 truncate text-xs text-red-600" title={doc.error}>{doc.error}</p>}</div><span className={`hidden items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold sm:flex ${doc.status === 'Ready' ? 'bg-emerald-50 text-emerald-700' : doc.status === 'Failed' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700'}`}>{doc.status === 'Ready' ? <CheckCircle2 size={14}/> : doc.status === 'Failed' ? <XCircle size={14}/> : <LoaderCircle size={14} className="animate-spin"/>}{doc.status}</span><button className="btn-ghost text-slate-400 hover:text-red-600" onClick={() => void remove(doc.id)} aria-label={`Delete ${doc.fileName}`}><Trash2 size={17}/></button></li>)}</ul>}</div>
  </div>
}
